---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
ms.openlocfilehash: 0e00adf736508e1bfc4f766eceda8c956411ec6e
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 02/17/2020
ms.locfileid: "77416637"
---
# <a name="c28105"></a>C28105

> Upozornění C28105: únik prostředku z důvodu výjimky

Zadaný prostředek není uvolněn, pokud je vyvolána výjimka. Příkaz určený cestou může vyvolat výjimku. Toto upozornění je podobné upozornění [C28103](../code-quality/c28103.md), s výjimkou případů, kdy v tomto případě je zahrnuta výjimka.

## <a name="example"></a>Příklad

Následující příklad kódu vygeneruje toto upozornění:

```cpp
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

Následující příklad kódu předchází tomuto upozornění:

```cpp
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
